# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voice_stream_pb2 as voice__stream__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voice_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceStreamerStub(object):
    """Service definition for voice streaming
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamVoice = channel.stream_stream(
                '/voice_stream.VoiceStreamer/StreamVoice',
                request_serializer=voice__stream__pb2.VoiceChunk.SerializeToString,
                response_deserializer=voice__stream__pb2.VoiceAck.FromString,
                _registered_method=True)


class VoiceStreamerServicer(object):
    """Service definition for voice streaming
    """

    def StreamVoice(self, request_iterator, context):
        """Bidirectional stream for voice data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamVoice': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamVoice,
                    request_deserializer=voice__stream__pb2.VoiceChunk.FromString,
                    response_serializer=voice__stream__pb2.VoiceAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice_stream.VoiceStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice_stream.VoiceStreamer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceStreamer(object):
    """Service definition for voice streaming
    """

    @staticmethod
    def StreamVoice(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voice_stream.VoiceStreamer/StreamVoice',
            voice__stream__pb2.VoiceChunk.SerializeToString,
            voice__stream__pb2.VoiceAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
