# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice_stream.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'voice_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12voice_stream.proto\x12\x0cvoice_stream\"i\n\nVoiceChunk\x12\x13\n\x0bsequence_id\x18\x01 \x01(\x03\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\x12\x15\n\rhubert_tokens\x18\x03 \x01(\x0c\x12\x19\n\x11speaker_embedding\x18\x04 \x01(\x0c\"/\n\x08VoiceAck\x12\x13\n\x0bsequence_id\x18\x01 \x01(\x03\x12\x0e\n\x06status\x18\x02 \x01(\t2T\n\rVoiceStreamer\x12\x43\n\x0bStreamVoice\x12\x18.voice_stream.VoiceChunk\x1a\x16.voice_stream.VoiceAck(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOICECHUNK']._serialized_start=36
  _globals['_VOICECHUNK']._serialized_end=141
  _globals['_VOICEACK']._serialized_start=143
  _globals['_VOICEACK']._serialized_end=190
  _globals['_VOICESTREAMER']._serialized_start=192
  _globals['_VOICESTREAMER']._serialized_end=276
# @@protoc_insertion_point(module_scope)
