# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice_stream.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'voice_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12voice_stream.proto\x12\tvoicecomm\"R\n\nAudioChunk\x12\x15\n\rencoded_frame\x18\x01 \x01(\x0c\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\x12\x17\n\x0fsequence_number\x18\x03 \x01(\x05\"(\n\x03\x41\x63k\x12\x10\n\x08received\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2D\n\x0bVoiceStream\x12\x35\n\x08Transmit\x12\x15.voicecomm.AudioChunk\x1a\x0e.voicecomm.Ack\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=33
  _globals['_AUDIOCHUNK']._serialized_end=115
  _globals['_ACK']._serialized_start=117
  _globals['_ACK']._serialized_end=157
  _globals['_VOICESTREAM']._serialized_start=159
  _globals['_VOICESTREAM']._serialized_end=227
# @@protoc_insertion_point(module_scope)
