# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import voice_stream_pb2 as voice__stream__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voice_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceStreamStub(object):
    """The VoiceStream service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transmit = channel.stream_unary(
                '/voicecomm.VoiceStream/Transmit',
                request_serializer=voice__stream__pb2.AudioChunk.SerializeToString,
                response_deserializer=voice__stream__pb2.Ack.FromString,
                _registered_method=True)


class VoiceStreamServicer(object):
    """The VoiceStream service definition.
    """

    def Transmit(self, request_iterator, context):
        """Client-to-server streaming RPC for sending audio chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transmit': grpc.stream_unary_rpc_method_handler(
                    servicer.Transmit,
                    request_deserializer=voice__stream__pb2.AudioChunk.FromString,
                    response_serializer=voice__stream__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voicecomm.VoiceStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voicecomm.VoiceStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceStream(object):
    """The VoiceStream service definition.
    """

    @staticmethod
    def Transmit(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/voicecomm.VoiceStream/Transmit',
            voice__stream__pb2.AudioChunk.SerializeToString,
            voice__stream__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
